DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        BRAND_ID BIGINT NOT NULL,
                        START_DATE TIMESTAMP NOT NULL,
                        END_DATE TIMESTAMP NOT NULL,
                        PRICE_LIST INTEGER NOT NULL,
                        PRODUCT_ID BIGINT NOT NULL,
                        PRIORITY INTEGER NOT NULL,
                        PRICE DOUBLE NOT NULL,
                        CURR VARCHAR(3) NOT NULL
);