{
 "title": "Prices Api Dashboard",
 "time": { "from": "now-4h", "to": "now" },
 "panels": [
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  100 * sum(increase(api_requests_total{flow=\"price_detail\", type=~\"success|bad_request|not_found|cache_invalidation\"}[$__range])) \n  / \n  sum(increase(api_requests_total{flow=\"price_detail\", type=~\"success|error|bad_request|not_found|cache_invalidation\"}[$__range]))\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (\n  increase(api_requests_total{\n    flow=\"price_detail\", \n    type!~\"database_fetch|fallback\"\n  }[$__interval])\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Database Fetches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{type=\"database_fetch\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Cache Invalidations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{type=\"cache_invalidation\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Fallback Executions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{type=\"fallback\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Errors (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{type=\"error\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Bad Requests (400)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{type=\"bad_request\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Not Found (404)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{type=\"not_found\"}[$__rate_interval])) or vector(0)"
    }
   ]
  }
 ]
}